### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by fleetwoodmac** [samrocketman/git-identity-manager#7]
Hi! 

I made a homebrew formula for your project if you'd like to review it:

https://github.com/fleetwoodmac/homebrew-git-identity-manager/tree/main

It's been really helpful to me, and I just wanted a quicker way to install it/uninstall it!

**Comment by samrocketman** [comment]
Cool!  Looks like it is pointing at your fork instead of this one.  And your fork appears to be behind in releases v0.11 is out

**Comment by fleetwoodmac** [comment]
Yes, I made a note in both the fork as well as the repo for the brew formula that the release numbers and the SHAs for the release tar.gz are going to be different unfortunately. 

In order to make a homebrew tap and autoupdate the link, you need to own the repo that the binaries are coming from because of the the GitHub action that updates the formula. I was not able to really figure out a way to get the release numbers to match the ones here. 

I basically used a fork and the GitHub action/app Pull by wei to automatically pull any changes you make. Then in that fork, I use the GitHub tag action by mathieudutour to autogenerate a tag number on a push containing the commit message 'release' as I noticed that in your releases you always use that word when releasing a new version. I was not really able spend time to it to autoname it the same release number.  I then use the Release action by ncipollo to create a release based on that tag, and then the auto bump action by dawidd66 to update the link on the brew formula repo (again, pointing at my fork because you need to own the repo to run the action I think). This creates a PR on the homebrew formula repo, which I use actions by juliangruber to find and auto merge it.

If anyone has a good solution for this I would be happy to try it out!

**Comment by fleetwoodmac** [comment]
Small update, I think this is much better (and I think it works but we will see whenever your next release is!). I scrapped the fork and old formula, and created a new one [here](https://github.com/fleetwoodmac/homebrew-git-identity-manager). Instead of the approach [here](https://github.com/samrocketman/git-identity-manager/issues/7#issuecomment-2252653549), I tried setting up a GitHub action that runs hourly that fetches the latest release on your repo, and then feeds that to the auto-bump script. This seems to update fine, so now the URL points directly to your repo, and the SHA's should match!

**Comment by samrocketman** [comment]
Ok no worries! If there’s something I can set up on my side to facilitate I am happy to (I don’t know if GitHub supports that).

I was okay with your fork as well whatever works best for you.

With regard to schedule I suggest weekly.  I normally only make changes when absolutely necessary.  Sometimes there’s years between releases but that’s because I like using it as is.  It is still maintained as bug reports or feature requests come in (they’re just rare).

**Comment by samrocketman** [comment]
Could you open a PR to my README adding a section for homebrew and linking to your repo?

**Comment by fleetwoodmac** [comment]
I will definitely let you know if something can be done to make the auto-update work better or if it doesn't whenever properly when a new release comes out! I made a test repo and the workflow does seem to update the link correctly based on the output logs from the Github action I saw.  Merged your suggestion for the cron job, and submitted a PR with updates to the README as requested!
